In [4]:
import numpy as np

In [5]:
##------------- DataTypes & Attributes

In [45]:
#NumPy main datatype is ndarray
a1=np.array([1,2,3])
a1

array([1, 2, 3])

In [7]:
type(a1)

numpy.ndarray

In [54]:
a2=np.array([[1,2,3],[4,5,6]])
a3=np.array([[1,2,3,4],[9,8,7,6],[4,6,2,4],[43,4,34,23]])

In [9]:
a1.shape

(4,)

In [10]:
a2.shape

(2, 4)

In [11]:
a3.shape

(4, 4)

In [12]:
a1.ndim,a2.ndim,a3.ndim

(1, 2, 2)

In [13]:
a1.size,a2.size,a3.size

(4, 8, 16)

In [14]:
type(a1),type(a2),type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [15]:
#-----------Create a DataFrame from a Numpy array

In [16]:
import pandas as pd
df=pd.DataFrame(a3)
df

    0  1   2   3
0   1  2   3   4
1   9  8   7   6
2   4  6   2   4
3  43  4  34  23

In [17]:
##-----------------------Creating arrays

In [18]:
sample_arrays=np.array([1,2,3,4])
sample_arrays

array([1, 2, 3, 4])

In [19]:
ones=np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
type(ones)

numpy.ndarray

In [21]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
#range array

range_array= np.arange(0,10,2)

In [23]:
range_array

array([0, 2, 4, 6, 8])

In [24]:
# random array
random_array=np.random.randint(0,10,size=(3,5))

In [25]:
random_array

array([[2, 3, 4, 5, 3],
       [1, 5, 7, 0, 2],
       [3, 0, 6, 6, 1]], dtype=int32)

In [26]:
# random array of indexes between 0 to 1

In [27]:
rand_array=np.random.random((5,3))
rand_array

array([[0.01321274, 0.1101943 , 0.43955159],
       [0.93903668, 0.54385692, 0.50251437],
       [0.87483042, 0.39270708, 0.97485004],
       [0.49700443, 0.57480674, 0.54429269],
       [0.4263445 , 0.88504524, 0.65114382]])

In [28]:
#----------Pseudo-Random Numbers


randome_array4=np.random.randint(10,size=(5,3))

In [29]:
randome_array4

array([[8, 4, 4],
       [7, 0, 2],
       [8, 6, 7],
       [2, 7, 1],
       [6, 1, 1]], dtype=int32)

In [30]:
##-----Viewing arrays and matrices

In [31]:
np.unique(randome_array4)

array([0, 1, 2, 4, 6, 7, 8], dtype=int32)

In [32]:
a1

array([1, 2, 3, 4])

In [33]:
a2

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [34]:
a3

array([[ 1,  2,  3,  4],
       [ 9,  8,  7,  6],
       [ 4,  6,  2,  4],
       [43,  4, 34, 23]])

In [35]:
a3[:4,:1]

array([[ 1],
       [ 9],
       [ 4],
       [43]])

In [36]:
a4=np.random.randint(10,size=(2,3,4,5))
a4

array([[[[0, 9, 4, 6, 2],
         [9, 3, 7, 3, 3],
         [6, 3, 3, 5, 9],
         [8, 1, 6, 5, 1]],

        [[1, 9, 9, 2, 3],
         [4, 9, 3, 4, 4],
         [9, 3, 9, 0, 4],
         [4, 0, 1, 4, 1]],

        [[8, 7, 6, 6, 1],
         [7, 0, 4, 7, 2],
         [5, 7, 4, 9, 7],
         [2, 2, 5, 0, 0]]],


       [[[8, 2, 7, 9, 8],
         [8, 0, 1, 4, 2],
         [9, 5, 0, 5, 2],
         [0, 6, 5, 6, 9]],

        [[3, 8, 3, 6, 4],
         [1, 8, 2, 4, 5],
         [5, 2, 6, 4, 5],
         [7, 6, 2, 1, 2]],

        [[8, 7, 0, 5, 3],
         [0, 9, 1, 1, 3],
         [2, 6, 6, 8, 0],
         [5, 8, 5, 7, 0]]]], dtype=int32)

In [37]:
#Get the first 4 number of the inner most arrays

In [38]:
a4[:,:,:,:4]

array([[[[0, 9, 4, 6],
         [9, 3, 7, 3],
         [6, 3, 3, 5],
         [8, 1, 6, 5]],

        [[1, 9, 9, 2],
         [4, 9, 3, 4],
         [9, 3, 9, 0],
         [4, 0, 1, 4]],

        [[8, 7, 6, 6],
         [7, 0, 4, 7],
         [5, 7, 4, 9],
         [2, 2, 5, 0]]],


       [[[8, 2, 7, 9],
         [8, 0, 1, 4],
         [9, 5, 0, 5],
         [0, 6, 5, 6]],

        [[3, 8, 3, 6],
         [1, 8, 2, 4],
         [5, 2, 6, 4],
         [7, 6, 2, 1]],

        [[8, 7, 0, 5],
         [0, 9, 1, 1],
         [2, 6, 6, 8],
         [5, 8, 5, 7]]]], dtype=int32)

In [61]:
##------------ Manipulating & Comapring arrys------------------

In [40]:
# Arithmetic

In [46]:
a1

array([1, 2, 3])

In [47]:
ones=np.ones(3)
ones

array([1., 1., 1.])

In [48]:
a1+ones

array([2., 3., 4.])

In [49]:
a1-ones

array([0., 1., 2.])

In [50]:
a1* ones

array([1., 2., 3.])

In [51]:
a2

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [55]:
a1*a2

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [56]:
a1 / ones

array([1., 2., 3.])

In [58]:
#floor division removes decimal
a2 // a1

array([[1, 1, 1],
       [4, 2, 2]])

In [59]:
np.square(a2)

array([[ 1,  4,  9],
       [16, 25, 36]])

In [60]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [64]:
a1%2

array([1, 0, 1])

In [66]:
###----------Aggregation-------------
#Perfoming the same operation on a number of things

In [67]:
listy_list=[1,2,3]
type(listy_list)

list

In [68]:
sum(listy_list)

6

In [70]:
type(a1)

numpy.ndarray

In [72]:
np.sum(a1)

np.int64(6)

In [73]:
sum(a1)

np.int64(6)

In [74]:
#Use Python methods on pythons datatypes and use
#Numpy methouds on numpy arrays

In [76]:
#Create a massive array

In [77]:
massive_array= np.random.random(100000)

In [81]:
massive_array[:10]

array([0.07793267, 0.70813397, 0.87449087, 0.4419515 , 0.46875448,
       0.83698626, 0.95623911, 0.27344955, 0.75685422, 0.04214552])

In [92]:
%timeit sum(massive_array) #python sum()
%timeit np.sum(massive_array) #numpy np.ssum()

11.7 ms ± 584 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
48.2 μs ± 3.77 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

In [84]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
np.mean(a2)

np.float64(3.5)

In [86]:
np.std(a2)

np.float64(1.707825127659933)

In [88]:
### -------------------Reshaping and Transpoising array

In [90]:
a2.shape

(2, 3)

In [ ]:
#----

In [94]:
a3.shape

(4, 4)

In [97]:
a3.shape

(4, 4)

In [101]:
###Transpose

In [105]:
a2.shape

(2, 3)

In [104]:
a2.T.shape

(3, 2)

In [106]:
##-------- Dot Product

In [122]:
np.random.seed(0)

mat1 = np.random.randint(10,size=(5,3))
mat2 = np.random.randint(10,size=(5,3))

In [123]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]], dtype=int32)

In [124]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]], dtype=int32)

In [125]:
mat1 * mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]], dtype=int32)

In [128]:
#Dot Product

In [130]:
mat1.T.shape

(3, 5)

In [133]:
mat3=np.dot(mat1,mat2.T)

In [134]:
mat3.shape

(5, 5)

In [135]:
mat3

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]], dtype=int32)

In [136]:
##------Dot Product Example(nut butter sales)

In [138]:
np.random.seed(0)
#Number of jars sold
sales_amounts = np.random.randint(20, size=(5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]], dtype=int32)

In [139]:
#Create Weekly_sales Datframe
weeky_sales=pd.DataFrame(sales_amounts,index=["Mon","Tue","Wed","Thu","Fri"],columns=["Almond Butter","Peanut Butter","Cashew Butter"])
weeky_sales

     Almond Butter  Peanut Butter  Cashew Butter
Mon             12             15              0
Tue              3              3              7
Wed              9             19             18
Thu              4              6             12
Fri              1              6              7

In [146]:
#create Pirce array
prices=np.array([10,8,12])

#Create Butter Prices DataFrame
butter_prices = pd.DataFrame(prices.reshape(1,3),index=["Price"],columns=[["Almond Butter","Peanut Butter","Cashew Butter"]])
butter_prices

      Almond Butter Peanut Butter Cashew Butter
Price            10             8            12

In [149]:
#Shape arent alighed lets transpose
total_sales=prices.dot(sales_amounts.T)
total_sales

array([240, 138, 458, 232, 142])

In [150]:
#Create daily sales
butter_prices

      Almond Butter Peanut Butter Cashew Butter
Price            10             8            12

In [151]:
weeky_sales["Daily-Sales"]=total_sales

In [153]:
weeky_sales=weeky_sales.drop("Daily-Sales",axis=1)

In [155]:
weeky_sales.shape , butter_prices.shape

((5, 3), (1, 3))

In [163]:
butter_prices.dot(weeky_sales.T)

NotImplementedError: Can only union MultiIndex with MultiIndex or Index of tuples, try mi.to_flat_index().union(other) instead.

In [164]:
#--------- Comparison Operators

In [165]:
a1

array([1, 2, 3])

In [166]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [169]:
a2>=a1

array([[ True,  True,  True],
       [ True,  True,  True]])

In [170]:
#Sorting Arrays--------------

In [173]:
rand_arr=np.random.randint(10,size=(3,5))
rand_arr

array([[7, 2, 0, 0, 4],
       [5, 5, 6, 8, 4],
       [1, 4, 9, 8, 1]], dtype=int32)

In [174]:
np.sort(rand_arr)

array([[0, 0, 2, 4, 7],
       [4, 5, 5, 6, 8],
       [1, 1, 4, 8, 9]], dtype=int32)

In [175]:
np.argsort(rand_arr)

array([[3, 2, 1, 4, 0],
       [4, 0, 1, 2, 3],
       [0, 4, 1, 3, 2]])

In [176]:
a1

array([1, 2, 3])

In [177]:
np.argsort(a1)

array([0, 1, 2])

In [178]:
np.argmin(a1)

np.int64(0)

In [181]:
np.argmax(rand_arr,axis=1)

array([0, 3, 2])

In [182]:
#### ^^^^^ Practical Example _Numpy In Action!!!!!!!

<img src="panda.png">

In [186]:
#Turn an image into a numpy array

In [189]:
from matplotlib.image import imread
panda=imread("panda.png")
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0.05098039, 0.03137255],
        ...,
        [0.02745098, 0.02745098, 0.03529412],
        [0.02745098, 0.02745098, 0.03529412],
        [0.02745098, 0.02745098, 0.03529412]],

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.12156863, 0.0627451 , 0.04313726],
        ...,
        [0.02352941, 0.02352941, 0.03137255],
        [0.02352941, 0.02352941, 0.03137255],
        [0.02352941, 0.02352941, 0.03137255]],

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.12156863, 0.0627451 , 0.04313726],
        ...,
        [0.02352941, 0.02352941, 0.03137255],
        [0.02352941, 0.02352941, 0.03137255],
        [0.02352941, 0.02352941, 0.03137255]]],
      shape=(2330, 3500, 3), dtype=float32)

In [190]:
panda.size, panda.shape,panda.ndim

(24465000, (2330, 3500, 3), 3)

<img src="car-photo.png">

In [193]:
car= imread("car-photo.png")

In [194]:
car

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]],

       [[0.44313726, 0.43529412, 0.40392157, 1.        ],
        [0.3137255 , 0.31764707, 0.27450982, 1.        ],
        [0.2       , 0.21176471, 0.14117648, 1.        ],
        ...,
        [0.5058824 , 0.5372549 , 0.4117647 , 1.        ],
        [0.49803922, 0.52156866, 0.39607844, 1.        ],
        [0.4       , 0.42745098, 0.34117648, 1.        ]],

       [[0.39607844, 0.38039216, 0.34117648, 1.        ],
        [0.31764707, 0.3137255 , 0.27450982, 1.        ],
        [0.28627452, 0.29411766, 0.24705882, 1.        ],
        ...,
        [0.44705883, 0.45882353, 0.32156864, 1.        ],
        [0.45882353, 0.48235294, 0.3529412 , 1.        ],
        [0.4509804 , 0.49019608, 0.38039216, 1.        ]],

       ...,

       [[0.47058824, 0.57254905, 0.6313726 , 1.        ],
        [0.4392157 , 0.53333336, 0.5882353 , 1.        ],
        [0.48235294, 0.5803922 , 0.6392157 , 1.        ],
        ...,
        [0.6156863 , 0.7529412 , 0.827451  , 1.        ],
        [0.61960787, 0.7607843 , 0.83137256, 1.        ],
        [0.5921569 , 0.73333335, 0.7921569 , 1.        ]],

       [[0.4745098 , 0.5803922 , 0.6392157 , 1.        ],
        [0.47058824, 0.58431375, 0.63529414, 1.        ],
        [0.4117647 , 0.5019608 , 0.5529412 , 1.        ],
        ...,
        [0.54901963, 0.6784314 , 0.74509805, 1.        ],
        [0.65882355, 0.8117647 , 0.8862745 , 1.        ],
        [0.60784316, 0.74509805, 0.8117647 , 1.        ]],

       [[0.4745098 , 0.57254905, 0.627451  , 1.        ],
        [0.49411765, 0.6       , 0.65882355, 1.        ],
        [0.49019608, 0.5921569 , 0.64705884, 1.        ],
        ...,
        [0.5294118 , 0.63529414, 0.69803923, 1.        ],
        [0.5529412 , 0.67058825, 0.7372549 , 1.        ],
        [0.6156863 , 0.73333335, 0.8       , 1.        ]]],
      shape=(431, 575, 4), dtype=float32)

In [195]:
dog=imread("dog-photo.png")

In [196]:
dog

array([[[0.70980394, 0.80784315, 0.88235295, 1.        ],
        [0.72156864, 0.8117647 , 0.8862745 , 1.        ],
        [0.7411765 , 0.8156863 , 0.8862745 , 1.        ],
        ...,
        [0.49803922, 0.6862745 , 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8352941 , 1.        ]],

       [[0.69411767, 0.8039216 , 0.8862745 , 1.        ],
        [0.7019608 , 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49411765, 0.68235296, 0.84313726, 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ]],

       [[0.6901961 , 0.8       , 0.88235295, 1.        ],
        [0.69803923, 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49803922, 0.6862745 , 0.84313726, 1.        ],
        [0.49803922, 0.6862745 , 0.84313726, 1.        ]],

       ...,

       [[0.9098039 , 0.81960785, 0.654902  , 1.        ],
        [0.8352941 , 0.7490196 , 0.6509804 , 1.        ],
        [0.72156864, 0.6313726 , 0.5372549 , 1.        ],
        ...,
        [0.01568628, 0.07058824, 0.02352941, 1.        ],
        [0.03921569, 0.09411765, 0.03529412, 1.        ],
        [0.03921569, 0.09019608, 0.05490196, 1.        ]],

       [[0.9137255 , 0.83137256, 0.6784314 , 1.        ],
        [0.8117647 , 0.7294118 , 0.627451  , 1.        ],
        [0.65882355, 0.5686275 , 0.47843137, 1.        ],
        ...,
        [0.00392157, 0.05490196, 0.03529412, 1.        ],
        [0.03137255, 0.09019608, 0.05490196, 1.        ],
        [0.04705882, 0.10588235, 0.06666667, 1.        ]],

       [[0.9137255 , 0.83137256, 0.68235296, 1.        ],
        [0.76862746, 0.68235296, 0.5882353 , 1.        ],
        [0.59607846, 0.5058824 , 0.44313726, 1.        ],
        ...,
        [0.03921569, 0.10196079, 0.07058824, 1.        ],
        [0.02745098, 0.08235294, 0.05882353, 1.        ],
        [0.05098039, 0.11372549, 0.07058824, 1.        ]]],
      shape=(432, 575, 4), dtype=float32)